apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: mongo
          #          image: docker.io/bitnami/mongodb
          image: mongo
          # args: ["--dbpath", "/data/db"]
          env:
            #            - name: "MONGODB_ROOT_USER"
            - name: "MONGO_INITDB_ROOT_USERNAME"
              value: root
            #            - name: "MONGODB_ROOT_PASSWORD"
            - name: "MONGO_INITDB_ROOT_PASSWORD"
              value: example
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - mountPath: "/data/db"
              name: mediavolume
      volumes:
        - name: mediavolume
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: mongo-express
          image: mongo-express
          env:
            - name: "ME_CONFIG_MONGODB_ADMINUSERNAME"
              value: root
            - name: "ME_CONFIG_MONGODB_ADMINPASSWORD"
              value: example
            - name: "ME_CONFIG_MONGODB_URL"
              value: "mongodb://root:example@mongo:27017/"
          ports:
            - containerPort: 8081
              name: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  type: LoadBalancer
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
